### PR TITLE
Updates Critical Section API

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Description:
This Pull Request implements a SPStorage block-based API. This is a required step to shift over NSManagedObjectContext's blocks mechanism.

#### Details:
This is a required step towards implementing a workaround for issue #436. I'm splitting this in two Pull Requests, to ease code review.

Thanks!

### CODE REVIEW

**Comment by jleandroperez** [comment]
@astralbodies may i bother you with a code review?.

Thanks Aaron!!

**Comment by astralbodies** [comment]
Reviewing this now @jleandroperez - sorry for the delay.

**Comment by astralbodies** [comment]
Even though this isn't a necessary change I think the block demarcation of the unit of work makes complete sense. Semaphores are just stabby. 

:shipit:

**Comment by jleandroperez** [comment]
@astralbodies Again, thanks Aaron!. I'm in your debt!

**Pull request merged**
