### PR TITLE
Add optional forgot password link

### PR DESCRIPTION
**Pull request by prvnl**
With this PR, you can add an optional Forgot Password button to the Login ViewController (Ref: #155). This button is only shown when is explicitly activated and an valid URL is supplied using a localized string. By using the localized string, you can set specific URL's per language. This forgot password button switches place with the TOS button, so it doesn't take extra space in the Login ViewController.

To activate the button use: `[SPAuthenticationConfiguration sharedInstance].showForgotPasswordButton = YES;`
The localized string that should be used for the Forgot Password URL is: `"Forgot Password URL"`

This PR also changes the TOS URL to a localized custom TOS URL using: `"TOS URL"`. if it's not supplied and/or valid, it uses the default Simperium TOS.

Hope it helps!

Regards Patrick

### CODE REVIEW

**Comment by jleandroperez** [comment]
@prvnl sorry it took so long to address this issue!. 

Since this PR cannot be merged, i've created a new branch, and [cherry picked all of your commits here](https://github.com/Simperium/simperium-ios/pull/465).

I've introduced a couple modifications:

- `SPAuthenticationConfiguration` now has `forgotPasswordURL` and `termsOfServiceURL` properties. Removing any of them both will cause the links not to show up.
- `SPForgotPWViewController` and `SPTOSViewController` have been merged into `SPWebViewController`.

Usage would be:

`[[SPAuthenticationConfiguration sharedInstance] setTermsOfServiceURL:NSLocalizedString(....)];`

*Thanks so much* for helping us out!. Only pending is OSX, which will be addressed shortly.

**Comment by prvnl** [comment]
@jleandroperez you're welcome! I'll give it a try the coming week, thanks for all the work!

**Comment by jleandroperez** [comment]
@prvnl awesome! thank you sir!

**Comment by prvnl** [comment]
@jleandroperez it works great, nice modifications! Thanks for making this generally available in the framework!

If someone is interested in a forgot password mechanism for Simperium, they could use the basis of https://github.com/prvnl/simperium-user-manager to support this feature.

**Comment by jleandroperez** [comment]
@prvnl *Thank you* Patrick!!

**Pull request closed without merging**
