### PR TITLE
SPPersistentMutableDictionary: Adds Error 516 Failsafe

### LINKED ISSUE #364: Crash in [SPPersistentMutableDictionary persistentStoreCoordinator]
We have a fairly large number of such crashes:

```
Thread : Crashed: com.simperium.processor.TestEntity
0  libsystem_kernel.dylib         0x3b7221f0 __pthread_kill + 8
1  libsystem_pthread.dylib        0x3b78a7b7 pthread_kill + 58
2  libsystem_c.dylib              0x3b6d2ff9 abort + 76
3  xxxxxxxxxx                     0x00b60b05 -[SPPersistentMutableDictionary persistentStoreCoordinator] (SPPersistentMutableDictionary.m:339)
4  xxxxxxxxxx                     0x00b606a1 -[SPPersistentMutableDictionary managedObjectContext] (SPPersistentMutableDictionary.m:300)
5  xxxxxxxxxx                     0x00b5e825 -[SPPersistentMutableDictionary count] (SPPersistentMutableDictionary.m:59)
6  xxxxxxxxxx                     0x00b4d223 -[SPChangeProcessor enumeratePendingChangesForBucket:block:] (SPChangeProcessor.m:674)
7  xxxxxxxxxx                     0x00b710e3 __43-[SPWebSocketChannel sendChangesForBucket:]_block_invoke346 (SPWebSocketChannel.m:538)
8  libdispatch.dylib              0x3b656d53 _dispatch_call_block_and_release + 10
9  libdispatch.dylib              0x3b65bcbd _dispatch_queue_drain + 488
10 libdispatch.dylib              0x3b658c6f _dispatch_queue_invoke + 42
11 libdispatch.dylib              0x3b65c5f1 _dispatch_root_queue_drain + 76
12 libdispatch.dylib              0x3b65c8dd _dispatch_worker_thread2 + 56
13 libsystem_pthread.dylib        0x3b787c17 _pthread_wqthread + 298
```

Note that TestEntity should have no sync activity, as no object of that entity should ever be created.

### PR DESCRIPTION
**Pull request by jleandroperez**
This PR adds a check, so that we prevent Cocoa Error 516 (File already exists).

Fixes #364

### CODE REVIEW

**Comment by mmilen** [comment]
I have added the patch, I will let you know as soon as I hear from testers. Never run into the issue on my development systems.

**Comment by jleandroperez** [comment]
@mmilen hello there,

May i ask you if you've been able to verify this fix?. Thanks in advance!

**Comment by mmilen** [comment]
Ooops,  I'm sorry I forgot you. The fix worked like a charm.


*Milen Milkovski*
CEO / Lead Developer
L'Atelier D'Ema
milen@emabridge.com

**Comment by jleandroperez** [comment]
Awesome, thanks for checking sir!

**Pull request merged**
